/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import snmp.SNMPGetException;

/**
 *
 * @author Praktikant
 */
public class MainInterface extends javax.swing.JFrame {
    private MainInterfaceWrapper wrapper;
    private IridaBindingGroup ibg;
    /**
     * Creates new form NewMainJFrame
     */
    public MainInterface() throws SNMPGetException, Exception {
        initComponents();
        
        wrapper = new MainInterfaceWrapper();
        ibg = new IridaBindingGroup(wrapper);
        
        ibg.add("ip", fieldIp);
        ibg.add("community", fieldCommunity);
        
        ArrayList<BindingColumn> listTableSwitches = new ArrayList<BindingColumn>();
        listTableSwitches.add(new BindingColumn("ip"));
        listTableSwitches.add(new BindingColumn("model"));
        listTableSwitches.add(new BindingColumn("gatewayMac"));
        //listTableSwitches.add(new BindingColumn("status"));
        ibg.add("curSwitch", "switches", listTableSwitches, tableSwitches);
        
        
        
        ArrayList<BindingColumn> listTableVlans = new ArrayList<BindingColumn>();
        listTableVlans.add(new BindingColumn("vlanNbr"));
        listTableVlans.add(new BindingColumn("gatewayMacCheck"));
        listTableVlans.add(new BindingColumn("macCount"));
        ibg.add("vlan", "curSwitch.vlans", listTableVlans, tableVlans);

        ArrayList<BindingColumn> listTableMacs = new ArrayList<BindingColumn>();
        listTableMacs.add(new BindingColumn("address"));
        ibg.add("mac", "vlan.macs", listTableMacs, tableMacs);
        
        
        
        
        ArrayList<BindingColumn> listTablePorts = new ArrayList<BindingColumn>();
        listTablePorts.add(new BindingColumn("portNbr"));
        listTablePorts.add(new BindingColumn("portName"));
        listTablePorts.add(new BindingColumn("vlanSize"));
        listTablePorts.add(new BindingColumn("vlansString"));
        ibg.add("port", "curSwitch.ports", listTablePorts, tablePorts);
        
        ArrayList<BindingColumn> listTablePortVlans = new ArrayList<BindingColumn>();
        listTablePortVlans.add(new BindingColumn("vlanNbr"));
        ibg.add("vlanOnPort", "port.vlans", listTablePortVlans, tablePortVlans);
        
        

        ArrayList<BindingColumn> listTablePortToVlan = new ArrayList<BindingColumn>();
        listTablePortToVlan.add(new BindingColumn("portNbr"));
        listTablePortToVlan.add(new BindingColumn("portName"));
        listTablePortToVlan.add(new BindingColumn("vlanNbr"));
        listTablePortToVlan.add(new BindingColumn("macsSize"));
        ibg.add("portToVlan", "curSwitch.vlanToPortList", listTablePortToVlan, tablePortToVlan);
        //ibg.add("portToVlan", "vlanToPortList", listTablePortToVlan, tablePortToVlan);
        
        ArrayList<BindingColumn> listTableMacsPort = new ArrayList<BindingColumn>();
        listTableMacsPort.add(new BindingColumn("address"));
        ibg.add("portMac", "portToVlan.macs", listTableMacsPort, tableMacsPort);
        
        
        
        ArrayList<BindingColumn> listTableSwitchConnections = new ArrayList<BindingColumn>();
        listTableSwitchConnections.add(new BindingColumn("switchUp.ip"));
        listTableSwitchConnections.add(new BindingColumn("upPort.portNbr"));
        listTableSwitchConnections.add(new BindingColumn("switchDown.ip"));
        listTableSwitchConnections.add(new BindingColumn("downPort.portNbr"));
        listTableSwitchConnections.add(new BindingColumn("vlanErrorsString"));
        ibg.add("curSwitchConnection", "switchConnections", listTableSwitchConnections, tableSwitchConnections);
        
        ArrayList<BindingColumn> listTableUplinkDownlink = new ArrayList<BindingColumn>();
        listTableUplinkDownlink.add(new BindingColumn("switchIp"));
        listTableUplinkDownlink.add(new BindingColumn("portNbr"));
        listTableUplinkDownlink.add(new BindingColumn("isUplink"));
        listTableUplinkDownlink.add(new BindingColumn("problemVlans"));
        ibg.add("badPort", "badPorts", listTableUplinkDownlink, tableUplinkDownlink);
        
       
        ibg.bind();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInput = new javax.swing.JPanel();
        checkBtn = new javax.swing.JToggleButton();
        fieldIp = new javax.swing.JTextField();
        labelIp = new javax.swing.JLabel();
        labelCommunity = new javax.swing.JLabel();
        fieldCommunity = new javax.swing.JTextField();
        refreshSwitch = new javax.swing.JButton();
        panelVlanErrors = new javax.swing.JPanel();
        scrollpaneSwitchConnections = new javax.swing.JScrollPane();
        tableSwitchConnections = new javax.swing.JTable();
        scrollpaneUplinkDownlink = new javax.swing.JScrollPane();
        tableUplinkDownlink = new javax.swing.JTable();
        panelAllSwitches = new javax.swing.JPanel();
        scrollpaneSwitches = new javax.swing.JScrollPane();
        tableSwitches = new javax.swing.JTable();
        panelSelectedSwitch = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        scrollpaneVlans = new javax.swing.JScrollPane();
        tableVlans = new javax.swing.JTable();
        scrollpaneMacs = new javax.swing.JScrollPane();
        tableMacs = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        scrollpanePorts = new javax.swing.JScrollPane();
        tablePorts = new javax.swing.JTable();
        scrollpanePortVlans = new javax.swing.JScrollPane();
        tablePortVlans = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        scrollpanePortToVlan = new javax.swing.JScrollPane();
        tablePortToVlan = new javax.swing.JTable();
        scrollpaneMacsPort = new javax.swing.JScrollPane();
        tableMacsPort = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        checkBtn.setText("check");
        checkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBtnActionPerformed(evt);
            }
        });

        fieldIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIpActionPerformed(evt);
            }
        });

        labelIp.setText("IP");

        labelCommunity.setText("Community");

        refreshSwitch.setText("refresh");
        refreshSwitch.setEnabled(false);
        refreshSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshSwitchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelIp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCommunity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIp)
                    .addComponent(labelCommunity)
                    .addComponent(fieldCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBtn)
                    .addComponent(refreshSwitch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVlanErrors.setBorder(javax.swing.BorderFactory.createTitledBorder("Vlan errors"));

        tableSwitchConnections.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpaneSwitchConnections.setViewportView(tableSwitchConnections);

        tableUplinkDownlink.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpaneUplinkDownlink.setViewportView(tableUplinkDownlink);

        javax.swing.GroupLayout panelVlanErrorsLayout = new javax.swing.GroupLayout(panelVlanErrors);
        panelVlanErrors.setLayout(panelVlanErrorsLayout);
        panelVlanErrorsLayout.setHorizontalGroup(
            panelVlanErrorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVlanErrorsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVlanErrorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpaneSwitchConnections, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
                    .addComponent(scrollpaneUplinkDownlink))
                .addContainerGap())
        );
        panelVlanErrorsLayout.setVerticalGroup(
            panelVlanErrorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVlanErrorsLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(scrollpaneSwitchConnections, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneUplinkDownlink, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
        );

        panelAllSwitches.setBorder(javax.swing.BorderFactory.createTitledBorder("All switches"));

        tableSwitches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpaneSwitches.setViewportView(tableSwitches);

        javax.swing.GroupLayout panelAllSwitchesLayout = new javax.swing.GroupLayout(panelAllSwitches);
        panelAllSwitches.setLayout(panelAllSwitchesLayout);
        panelAllSwitchesLayout.setHorizontalGroup(
            panelAllSwitchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllSwitchesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpaneSwitches, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAllSwitchesLayout.setVerticalGroup(
            panelAllSwitchesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllSwitchesLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(scrollpaneSwitches, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        panelSelectedSwitch.setBorder(javax.swing.BorderFactory.createTitledBorder("Current switch"));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vlans"));

        tableVlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpaneVlans.setViewportView(tableVlans);

        tableMacs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpaneMacs.setViewportView(tableMacs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpaneVlans)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneMacs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpaneMacs, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(scrollpaneVlans, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ports"));

        tablePorts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpanePorts.setViewportView(tablePorts);

        tablePortVlans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpanePortVlans.setViewportView(tablePortVlans);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanePorts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanePortVlans, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpanePorts, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(scrollpanePortVlans, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ports and Vlans"));

        tablePortToVlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpanePortToVlan.setViewportView(tablePortToVlan);

        tableMacsPort.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollpaneMacsPort.setViewportView(tableMacsPort);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpanePortToVlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpaneMacsPort, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpanePortToVlan, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(scrollpaneMacsPort, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout panelSelectedSwitchLayout = new javax.swing.GroupLayout(panelSelectedSwitch);
        panelSelectedSwitch.setLayout(panelSelectedSwitchLayout);
        panelSelectedSwitchLayout.setHorizontalGroup(
            panelSelectedSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectedSwitchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSelectedSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelSelectedSwitchLayout.setVerticalGroup(
            panelSelectedSwitchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectedSwitchLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelVlanErrors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAllSwitches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSelectedSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelVlanErrors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAllSwitches, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelSelectedSwitch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBtnActionPerformed
       try {
          wrapper.checkSwitch();
          refreshSwitch.setEnabled(true);
       } catch (Exception ex) {
          refreshSwitch.setEnabled(true);
          Utility.showTimeoutError();
          throw new RuntimeException(ex);
       }
    
    }//GEN-LAST:event_checkBtnActionPerformed

    private void fieldIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIpActionPerformed

    private void refreshSwitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshSwitchActionPerformed
        // TODO add your handling code here:
        try {
            wrapper.refreshCurSwitch();
        } catch(Exception ex) {
            Utility.showTimeoutError();
            throw new RuntimeException(ex);
        }
    }//GEN-LAST:event_refreshSwitchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainInterface().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton checkBtn;
    private javax.swing.JTextField fieldCommunity;
    private javax.swing.JTextField fieldIp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelCommunity;
    private javax.swing.JLabel labelIp;
    private javax.swing.JPanel panelAllSwitches;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelSelectedSwitch;
    private javax.swing.JPanel panelVlanErrors;
    private javax.swing.JButton refreshSwitch;
    private javax.swing.JScrollPane scrollpaneMacs;
    private javax.swing.JScrollPane scrollpaneMacsPort;
    private javax.swing.JScrollPane scrollpanePortToVlan;
    private javax.swing.JScrollPane scrollpanePortVlans;
    private javax.swing.JScrollPane scrollpanePorts;
    private javax.swing.JScrollPane scrollpaneSwitchConnections;
    private javax.swing.JScrollPane scrollpaneSwitches;
    private javax.swing.JScrollPane scrollpaneUplinkDownlink;
    private javax.swing.JScrollPane scrollpaneVlans;
    private javax.swing.JTable tableMacs;
    private javax.swing.JTable tableMacsPort;
    private javax.swing.JTable tablePortToVlan;
    private javax.swing.JTable tablePortVlans;
    private javax.swing.JTable tablePorts;
    private javax.swing.JTable tableSwitchConnections;
    private javax.swing.JTable tableSwitches;
    private javax.swing.JTable tableUplinkDownlink;
    private javax.swing.JTable tableVlans;
    // End of variables declaration//GEN-END:variables
}
